apiVersion: 1

datasources:
  - name: XBOL Loki
    uid: xbol-loki
    type: loki
    access: proxy
    url: http://xbol-loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
