# vi: ft=hyprlang

windowrule {
  name = "dictate_feedback"
  match:title = dictate_feedback

  float = true
  size = 640 128
  move = ((monitor_w-window_w)/2) 35
  pin = true
  hyprbars:no_bar = true
  border_size = 0
  rounding = 8
  no_shadow = true
  animation = slide top
}

bind = CTRL, SPACE, exec, app2unit -- dictate begin
bindr = CTRL, SPACE, exec, /home/carlos/.cargo/bin/dictate end
binde = CTRL, SPACE, exec, /home/carlos/.cargo/bin/dictate heartbeat
bind = CTRL SHIFT, SPACE, exec, app2unit -- dictate cancel
