program_options:
  automount: true
  notify: true
  tray: auto
  file_manager: dolphin
  terminal: kitty

notifications:
  device_mounted: 10
  device_unmounted: 10
  device_unlocked: 10
  device_locked: 10
  job_failed: 30
  device_added: false
  device_removed: false
  browse: true
  umount: true
