#!/bin/bash
# Set mouse LED colors - Generated by cfg
PROFILE=0
DEVICE="warbling-mara"

# Profile 0 only (active profile)
ratbagctl $DEVICE profile active set $PROFILE
ratbagctl $DEVICE profile $PROFILE led 0 set color aa6176
ratbagctl $DEVICE profile $PROFILE led 1 set color b4befe
