#!/bin/bash
# Set mouse LED colors - Generated by cfg
DEVICE="warbling-mara"

# Profile 0 only (active profile)
ratbagctl $DEVICE profile 0 led 0 set color 89b4fa
ratbagctl $DEVICE profile 0 led 1 set color cba6f7
