# 1. Handle images
protocol file
mime image/*
action launch --type=overlay kitten icat --hold -- ${FILE_PATH}

# 2. Handle directories in Dolphin
protocol file
mime inode/directory
action launch --type=background app2unit -- dolphin ${FILE_PATH}

# 3. Handle all other files
protocol file
mime */*
action launch --type=tab nvim ${FILE_PATH}
