# vi: ft=hyprlang

windowrule {
  name = "clipse_scratch"
  match:class = clipse_scratch

  float = true
  size = 720 720
  hyprbars:no_bar = true
  center = true
  animation = slide top
  workspace = special:clipboard
}

bind = $mainMod, V, exec, hyprspace toggle clipboard
bind = $mainMod CTRL, V, exec, hyprspace raw clipboard
