# vi: ft=hyprlang

###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

# Take screenshot of window
bind = $mainMod, S, exec, pgrep -x app2unit -- slurp || app2unit -- hyprshot -o ~/Pictures/Screenshots --freeze -m window

# Take screenshot of region
bind = $mainMod SHIFT, S, exec, pgrep -x app2unit -- slurp || app2unit -- hyprshot -o ~/Pictures/Screenshots --freeze -m region

# Escape hatch: unfreeze desktop when hyprshot leaves hyprpicker running
bind = $mainMod CTRL, S, exec, pkill -x hyprpicker; pkill -x slurp; pkill -x hyprshot
