# vi: ft=hyprlang

# Quick Format citation dialog floats
windowrule {
  name = Zotero Quick Format
  match:title = Zotero Quick Format
  float = true
  center = true
}

###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

bind = $mainMod, Backspace, exec, zotero
