personality = "pragmatic"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
commit_attribution = ""
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"

[features]
codex_git_commit = false
memories = true
terminal_resize_reflow = true
goals = true

[shell_environment_policy]
inherit = "core"

[tui]
notifications = ["agent-turn-complete", "approval-requested"]
notification_method = "osc9"
notification_condition = "unfocused"
status_line = ["model-with-reasoning", "current-dir", "git-branch", "branch-changes", "run-state", "context-used", "five-hour-limit", "used-tokens", "task-progress"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/home/carlos/.dotfiles"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-api-admin"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-db-develop"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-web-admin"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-api-ticketing"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-web-client"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-api-client"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/xbol-app-client"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/workshop/xbol-tests"]
trust_level = "trusted"

[projects."/home/carlos/Development/CRI/se"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/infra-cloud"]
trust_level = "trusted"

[projects."/home/carlos/Development/XBOL/scripts/secrets"]
trust_level = "trusted"

[projects."/home/carlos/Development/ME/tailscale"]
trust_level = "trusted"

[projects."/home/carlos"]
trust_level = "trusted"

[projects."/home/carlos/.dotfiles/ai"]
trust_level = "trusted"

[plugins."codex-security@openai-curated"]
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true

[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp/authv2"
startup_timeout_sec = 30
tool_timeout_sec = 120
enabled = true
