# vi: ft=hyprlang

windowrule {
  name = "calculator"
  match:class = qalculate-gtk
  workspace = special:calculator
  float = true
  center = true
}

bind = $mainMod, C, exec, hyprspace toggle calculator
bind = $mainMod CTRL, C, exec, hyprspace raw calculator
