windows:
  installs: false
linux[whoami.distro^="Fedora"]:
  installs:
    cmd: |
      if ! id -nG "$USER" | grep -qw docker; then
        sudo groupadd -f docker
        sudo usermod -aG docker "$USER"
        newgrp docker
      fi
